# Generated by Django 3.2.3 on 2021-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptive_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
