# Generated by Django 3.2.3 on 2021-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_descriptive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
